import random  # TODO QUitar
from datetime import datetime
from typing import Literal

from schemas.acta import ActaBase, Comprension, Expresion, Tarea
from schemas.alumno import AlumnoBase
from schemas.usuario import UsuarioLogin

TIPOS_ACTA = Literal["Ordinaria", "Extraordinaria"]
IDIOMAS_DISPONIBLES = Literal[
    "Español", "English", "Català", "Français", "Chainese", "Deutsch"
]
HORARIOS = Literal["9:00"]

lista_acciones = [
    {"url": "acta/correct", "action_label": "Iniciar correcciones"},
    {"url": "acta/create", "action_label": "Crear una convocatoria nueva"},
    {"url": "acta/edit", "action_label": "Editar los parametros de una convocatoria"},
    {"url": "acta/list", "action_label": "Listar todas las convocatoria"},
    {"url": "alumno/activo", "action_label": "Listar convocatorias activas"},
    {"url": "alumno/edit", "action_label": "Editar alumnos"},
    {"url": "alumno/list", "action_label": "Listar alumnos"},
    {"url": "alumno/upload", "action_label": "Cargar CSV"},
    {"url": "usuario/create", "action_label": "Dar de alta usuario nuevo"},
    {"url": "usuario/list", "action_label": "Gestionar usuarios"},
    {"url": "usuario/edit", "action_label": "Editar usuario"},
]

fake_usuarios_DB = [
    UsuarioLogin(username="rick_sanchez", password="1234"),
    UsuarioLogin(username="morty_smith", password="1234"),
    UsuarioLogin(username="jerry_smith", password="1234"),
]

tarea = Tarea(alcance=1, coherencia=2, correccion=3, eficaciaC=4)
comprension = Comprension(puntuacionMaximaParte=30, puntuacion_tarea3=8, puntuacion_tarea2=6, puntuacion_tarea1=5, porcentaje=50, puntosConseguidos=2, observaciones='')
expresion = Expresion(tarea1=tarea, tarea2=tarea, observaciones='', pocentaje=50, puntosConseguidos=60, puntuacionMaximaParte=60)


fake_actas_DB = [
    ActaBase(  
        estado=True,
        lenguaje="Español",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        id="1",
    ),
   ActaBase(
        estado=True,
        lenguaje="English",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        id="2",
    ),
   ActaBase(
        estado=True,
        lenguaje="Català",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="3",
        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
    ),
   ActaBase(        
        estado=True,
        lenguaje="Français",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="4",
                comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
    ),
   ActaBase(        
        estado=True,
        lenguaje="Chainese",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
                comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        id="5",
    ),
   ActaBase(
        estado=True,
        lenguaje="Deutsch",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        id="6",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Español",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="7",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="English",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="8",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Català",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="9",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Français",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="10",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Chainese",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="11",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Deutsch",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="12",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Español",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="13",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="English",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="14",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Català",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="15",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Français",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="16",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Chainese",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="17",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Deutsch",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="18",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Español",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="19",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="English",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="20",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Català",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="21",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Français",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="22",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Chainese",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="23",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Deutsch",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="24",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Español",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="25",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="English",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="26",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Català",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="27",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Français",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="28",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Chainese",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="29",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=True,
        lenguaje="Deutsch",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="30",
    ),
   ActaBase(        comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Español",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="31",
    ),
   ActaBase(
     comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="English",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="32",
    ),
   ActaBase(
     comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Català",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="33",
    ),
   ActaBase( 
             comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Français",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="34",
    ),
   ActaBase(
      comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Chainese",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="35",
    ),
   ActaBase(
      comprensionAuditiva=comprension,
        comprensionLectora=comprension,
        expresionEscrita=expresion,
        expresionOral=expresion,
        estado=False,
        lenguaje="Deutsch",
        fecha=datetime.utcfromtimestamp(random.randint(1675000000, 1675999999)),
        tipo="Extraordinaria",
        id="36",
    ),
]

fake_alumnos_DB = [
    AlumnoBase(id="1", nombre="Bob", apellidos="Swanson"),
    AlumnoBase(id="2", nombre="Albert", apellidos="Swanson"),
    AlumnoBase(id="3", nombre="Billy", apellidos="Billington"),
    AlumnoBase(id="4", nombre="Rick", apellidos="Sanchez"),
    AlumnoBase(id="5", nombre="Jaimito", apellidos="Grimes"),
    AlumnoBase(id="6", nombre="Eustaquio", apellidos="Ramirez"),
    AlumnoBase(id="7", nombre="Firulais", apellidos="Gonzalez"),
    AlumnoBase(id="8", nombre="Waldo", apellidos="Emerson"),
]
