INSERT INTO pacle_db.rol (rol) VALUES  ('Administrador');
INSERT INTO pacle_db.rol (rol) VALUES  ('Gestor');
INSERT INTO pacle_db.rol (rol) VALUES  ('Corrector');
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson1'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson2'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson3'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson4'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson5'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson6'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson7'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson8'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson9'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson10'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson11'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson12'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson13'  );
INSERT INTO pacle_db.usuarios (    apellidos,    estado,    hashed_password,    nombre,    id_rol,    username  ) VALUES  (    'Swanson',    true,    'hashed_123',    'Bob',    1,    'bob_swanson14'  );
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 1);
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 2);
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 3);
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 4);
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 5);
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 6);
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 7);
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 8);
INSERT INTO pacle_db.tarea (    alcance,    coherencia,    correccion,    eficaciac,    id_corrector  ) VALUES  (1, 1, 1, 1, 9);
INSERT INTO pacle_db.expresion (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    tarea_1,    tarea_2  ) VALUES  ('Oral', 'Sin comentarios', 85, 25, 30, 1, 2);
INSERT INTO pacle_db.expresion (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    tarea_1,    tarea_2  ) VALUES  ('Escrita', 'Sin comentarios', 85, 25, 30, 3, 4);
INSERT INTO pacle_db.expresion (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    tarea_1,    tarea_2  ) VALUES  ('Oral', 'Sin comentarios', 85, 25, 30, 5, 6);
INSERT INTO pacle_db.expresion (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    tarea_1,    tarea_2  ) VALUES  ('Escrita', 'Sin comentarios', 85, 25, 30, 7, 8);
INSERT INTO pacle_db.expresion (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    tarea_1,    tarea_2  ) VALUES  ('Oral', 'Sin comentarios', 85, 25, 30, 1, 9);
INSERT INTO pacle_db.comprension (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    puntuacion_tarea_1,    puntuacion_tarea_2,    puntuacion_tarea_3  ) VALUES  (    'Auditiva',    'Sin comentarios',    95,    95,    100,    40,    40,    5  );
INSERT INTO pacle_db.comprension (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    puntuacion_tarea_1,    puntuacion_tarea_2,    puntuacion_tarea_3  ) VALUES  (    'Lectiva',    'Sin comentarios',    95,    95,    100,    40,    40,    5  );
INSERT INTO pacle_db.comprension (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    puntuacion_tarea_1,    puntuacion_tarea_2,    puntuacion_tarea_3  ) VALUES  (    'Auditiva',    'Sin comentarios',    95,    95,    100,    40,    40,    5  );
INSERT INTO pacle_db.comprension (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    puntuacion_tarea_1,    puntuacion_tarea_2,    puntuacion_tarea_3  ) VALUES  (    'Lectiva',    'Sin comentarios',    95,    95,    100,    40,    40,    5  );
INSERT INTO pacle_db.comprension (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    puntuacion_tarea_1,    puntuacion_tarea_2,    puntuacion_tarea_3  ) VALUES  (    'Auditiva',    'Sin comentarios',    95,    95,    100,    40,    40,    5  );
INSERT INTO pacle_db.comprension (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    puntuacion_tarea_1,    puntuacion_tarea_2,    puntuacion_tarea_3  ) VALUES  (    'Lectiva',    'Sin comentarios',    95,    95,    100,    40,    40,    5  );
INSERT INTO pacle_db.comprension (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    puntuacion_tarea_1,    puntuacion_tarea_2,    puntuacion_tarea_3  ) VALUES  (    'Auditiva',    'Sin comentarios',    95,    95,    100,    40,    40,    5  );
INSERT INTO pacle_db.comprension (    tipo,    observaciones,    porcentaje,    puntosConseguidos,    puntuacionMaxima,    puntuacion_tarea_1,    puntuacion_tarea_2,    puntuacion_tarea_3  ) VALUES  (    'Lectiva',    'Sin comentarios',    95,    95,    100,    40,    40,    5  );
INSERT INTO pacle_db.idiomas (lenguaje) VALUES ('Español');
INSERT INTO pacle_db.idiomas (lenguaje) VALUES ('Ingles');
INSERT INTO pacle_db.idiomas (lenguaje) VALUES ('Catalan');
INSERT INTO pacle_db.idiomas (lenguaje) VALUES ('Italiano');
INSERT INTO pacle_db.idiomas (lenguaje) VALUES ('Aleman');
INSERT INTO pacle_db.horarios (horario) VALUES ('09:00');
INSERT INTO pacle_db.horarios (horario) VALUES ('10:00');
INSERT INTO pacle_db.horarios (horario) VALUES ('11:00');
INSERT INTO pacle_db.horarios (horario) VALUES ('12:00');
INSERT INTO pacle_db.convocatorias (maxComprensionAuditiva,maxComprensionAuditiva,maxExpresionEscrita,maxExpresionOral,lenguaje,fecha,horario,estado) VALUES	 (100,100,100,100,1,'2023-03-08 00:00:00',1,true);
INSERT INTO pacle_db.convocatorias (maxComprensionAuditiva,maxComprensionAuditiva,maxExpresionEscrita,maxExpresionOral,lenguaje,fecha,horario,estado) VALUES	 (100,100,100,100,2,'2023-03-08 00:00:00',2,true);
INSERT INTO pacle_db.convocatorias (maxComprensionAuditiva,maxComprensionAuditiva,maxExpresionEscrita,maxExpresionOral,lenguaje,fecha,horario,estado) VALUES	 (100,100,100,100,3,'2023-03-08 00:00:00',3,true);
INSERT INTO pacle_db.convocatorias (maxComprensionAuditiva,maxComprensionAuditiva,maxExpresionEscrita,maxExpresionOral,lenguaje,fecha,horario,estado) VALUES	 (100,100,100,100,4,'2023-03-08 00:00:00',4,true);
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Albert', 'Swanson', 'A');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Bob', 'Swanson', 'B');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Billy', 'Swanson', 'C');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('David', 'Swanson', 'D');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Jaimito', 'Swanson', 'E');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Pedro', 'Swanson', 'F');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Albert', 'Swanson', 'G');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Albert', 'Swanson', 'H');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Albert', 'Swanson', 'I');
INSERT INTO pacle_db.alumnos (nombre, apellidos, dni) VALUES ('Albert', 'Swanson', 'J');
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (1, '2023-03-10 00:00:00', 1, 1, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (1, '2023-03-10 00:00:00', 1, 2, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (1, '2023-03-10 00:00:00', 1, 3, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (1, '2023-03-10 00:00:00', 1, 4, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (2, '2023-03-10 00:00:00', 1, 1, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (2, '2023-03-10 00:00:00', 1, 2, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (2, '2023-03-10 00:00:00', 1, 3, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (2, '2023-03-10 00:00:00', 1, 4, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (3, '2023-03-10 00:00:00', 1, 1, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (3, '2023-03-10 00:00:00', 1, 2, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (3, '2023-03-10 00:00:00', 1, 3, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (3, '2023-03-10 00:00:00', 1, 4, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (4, '2023-03-10 00:00:00', 1, 1, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (4, '2023-03-10 00:00:00', 1, 2, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (4, '2023-03-10 00:00:00', 1, 3, 2, 3, 4);
INSERT INTO pacle_db.actas (    idConvocatoria,    fecha,    idAlumno,    expresionEscrita,    expresion_oral,    comprension_lectiva,    comprensionAuditiva  ) VALUES  (4, '2023-03-10 00:00:00', 1, 4, 2, 3, 4);