"""Descripción de la migración

Revision ID: b242e54aa4ea
Revises: 
Create Date: 2023-04-10 22:28:42.813044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b242e54aa4ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
