"""Added default hashed password

Revision ID: ba0210a0a4e4
Revises: ea865b4b965b
Create Date: 2023-04-11 23:04:30.395749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0210a0a4e4'
down_revision = 'ea865b4b965b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
